PetFriendlyUniverse/Henry-Pf

api/src/controllers/productsControllers.js, api/src/handler/productsHandler.js, api/src/routes/productsRoutes.js
filter de back primera parte, por varios parametros
=> filter back Version 1

api/src/controllers/storeControllers.js, api/src/handler/storeHandler.js
filtros de stores perfectamente funcionales
=> Filter Store

client/src/App.jsx, client/src/pages/ecommerce/Checkout/Checkout.jsx, client/src/pages/ecommerce/ProductDetail/ProductDetail.jsx, client/src/pages/ecommerce/ShoppingCart/ShoppingCart.jsx
rutas de e-commerce y rfce en cada componente para renderizar un comentario en construccion
=> rutas de e-commerce

api/src/controllers/servicesControllers/walkersController.js, api/src/handler/servicesHandlers/walkersHandler.js, api/src/models/Walkers.js
Hay que arreglar el controller y handler de walkers, BENJAMIN
=> filtrado de walkers

api/src/controllers/servicesControllers/walkersController.js, api/src/handler/servicesHandlers/walkersHandler.js, api/src/routes/servicesRouters/walkersRouter.js
(agregada .post de ruta, controller, handler)
=> Walker editado 

client/src/App.jsx, client/src/components/NotFound/NotFound.jsx, client/src/pages/ecommerce/Shop/Shop.jsx
agregadas las rutas con el componente notFound
=> agregadas las rutas con el componente notFound

api/src/controllers/commentsController.js, api/src/controllers/favoriteController.js, api/src/controllers/storeControllers.js, api/src/controllers/userControllers.js, api/src/handler/favoriteHandler.js, api/src/routes/favoriteRouter.js
en controllers. Store, User y Comments
=> Traduccion de comentarios

api/src/controllers/productsControllers.js, api/src/handler/productsHandler.js, api/src/helpers/productsHelpers.js, api/src/routes/productsRoutes.js
agregado el filtrado múltiple de productos, con el ordenamiento, y unificada la ruta del get
=> /getproducts

client/tailwind.config.cjs
=> paleta de colores momentanea

api/src/helpers/productsHelpers.js, api/src/models/Product.js, api/src/randomGenerator.js
=> cambios de produtc con image y brand

client/src/pages/ecommerce/Profile/Profile.jsx
estilado de profile user hasta donde pude sin animaciones que tengo que ver eso, y sin info del back
=> Profile user

client/src/components/Button/LessButton.jsx, client/src/components/Button/MoarButton.jsx, client/src/components/CountProduct/CountProduct.jsx, client/src/components/CountProduct/CountProduct.module.css, client/src/components/NavBar/NavBar.jsx, client/src/pages/ecommerce/Checkout/Checkout.jsx
=> countproduct reutilizable, faltan funcionalidades

client/src/pages/ecommerce/Forms/FormProfile/Validations/Profile.js
hay 2 commit porque no le habia agregado el export a la funcion
=> correcion de validacion profile

api/src/controllers/productsControllers.js
solo pide los sigs atributos: id, name, price, img, weight, brand
=> getProduct solo pide atributos necesarios

api/src/models/User.js
se agrego, lastname, phone y se ordeno el modelo
=> modelo de user modificado

client/src/pages/ecommerce/Forms/FormCreateProduct/FormCreateProduct.jsx, client/src/pages/ecommerce/Forms/FormCreateProduct/Validation/ValidationProduts.js
validation de form de products
=> validation de form de products

client/src/pages/ecommerce/Shop/Shop.jsx
Vista desktop: 
Vista tablet: 
Vista mobile:
=> grueso del responsive del shop, falta afinar detalles

api/src/randomGenerator.js, client/src/App.jsx
SetTimeOut para Generators, Ruta de App para Form de Products, Form de User funcional
=> Solucion de problemas, form user funcional

api/src/helpers/productsHelpers.js, api/src/randomGenerator.js, client/src/redux/features/products/helpers/queryMaker.js
falta acomodar nomas los min-width de contenedores, pero lo funcional de los filtros ya estaría
=> Stefano - filtros- bugs fixeados (funcionan todos combinados)

api/src/controllers/productsControllers.js
=> Stefano - getProductsFilter trae solo info relevante al home y getAllProducts trae el stock

client/src/components/NavBar/components/searchForm.jsx
funcionamiento de busqueda de la search bar
=> Search Bar

client/src/pages/ecommerce/Shop/Shop.jsx, client/src/pages/ecommerce/Shop/components/Filters/components/List.jsx, client/tailwind.config.cjs
=> Stefano - refactor de renderizado condicional de btn / span y filtro seteado

client/src/App.css, client/src/index.css, client/src/pages/ecommerce/Checkout/Checkout.jsx, client/src/pages/ecommerce/ProductDetail/ProductDetail.jsx
fix del scroll horizontal en checkout y detail, estilo del scroll pasado a app.css
=> fix bug scroll horizontal

client/src/components/Paginator/Paginator.jsx
"breakpoints del min-width en el cardContainer y paginador  del shop"
=> breakpoints del min-width en el cardContainer y paginador  del shop

client/src/components/Button/LinkButton.jsx, client/src/components/NavBar/components/DropdownShop.jsx, client/src/components/SubCard/Subcard.jsx, client/src/pages/ecommerce/Checkout/Checkout.jsx
ModalShop sin scroll con 3 cards
ModalShop con scroll a partir de 4 cards en el carrito
Checkout dinamico
Finalizada la compra, alerta y redireccion a shop
=> modalShop, checkout

client/src/pages/ecommerce/ProductDetail/ProductDetail.jsx
agregada la logica para el product detail, agregar al carrito de compras
=> Logica Product Detail

client/src/pages/ecommerce/Forms/FormProfile/FormProfile.jsx, client/src/pages/ecommerce/Forms/Validations/Profile.js
validacion de contraseña repetida del putprofile anulada, no la pudimos hacer andar
=> putprofile

api/src/db.js, client/src/App.jsx, client/src/pages/ecommerce/Forms/FormCreateStore/FormCreateStore.jsx, client/src/pages/ecommerce/Forms/Validations/ValidateStore.js
Cree tambien una ruta en app para renderizar los componentes que necesito probar, vayan cambiandolo ustedes
=> form de stores funcional

api/index.js, client/src/components/Card/Card.jsx, client/src/components/Login/Login.jsx, client/src/components/Login/Login.module.css, client/src/components/NavBar/components/DropdownUser.jsx, client/src/main.jsx, client/src/pages/ecommerce/ProductDetail/ProductDetail.jsx
…rias imagenes"cards ahora puede renderizar un carousel para productos que tengas varias imagenes"
=> "cards ahora puede renderizar un carousel para productos que tengas varias imagenes"

api/index.js, api/src/controllers/productsControllers.js, api/src/handler/productsHandler.js, api/src/helpers/productsHelpers.js, client/src/main.jsx, client/src/redux/features/products/productsSlice.js
=> backend- products acepta rango de precio

api/src/controllers/servicesControllers/daycareController.js, api/src/controllers/servicesControllers/walkersController.js, api/src/controllers/storeControllers.js, api/src/controllers/userControllers.js, api/src/handler/userHandler.js, api/src/models/Daycare.js, api/src/models/Store.js, api/src/models/User.js, api/src/models/Walker.js, client/src/pages/ecommerce/Forms/FormModifyUser/FormModifyUser.jsx
hay que modificar todos los forms
=> modificacion de modelos para pasarela de pagos

api/src/controllers/storeControllers.js, api/src/controllers/userControllers.js, api/src/handler/productsHandler.js, api/src/handler/userHandler.js, api/src/models/Store.js, api/src/routes/index.js, api/src/routes/userRoutes.js, client/src/App.jsx, client/src/components/Button/LinkButton.jsx, client/src/components/CardStoreIdContainer/CardStoreIdContainer.jsx, client/src/components/Login/Login.jsx, client/src/components/NavBar/components/DropdownUser.jsx, client/src/pages/ecommerce/Forms/FormCreateProduct/FormCreateProduct.jsx, client/src/pages/ecommerce/Forms/FormModifyStore/FormModifyStore.jsx, client/src/pages/ecommerce/Profile/Profile.jsx, client/src/pages/ecommerce/Profile/components/TabStore.jsx, client/src/pages/ecommerce/Profile/components/TabUser.jsx, client/src/pages/ecommerce/Profile/hooks/useGetProductsByStoreId.js, client/src/redux/features/users/usersActions.js, client/src/redux/features/users/usersSlice.js
En general ya esta todo fixeado los errores faltan detalles de diseño, el cerrar sesion se mejoro
=> Federico--Cambios en form de productos, profile de store y arreglo de cerrar sesion

client/index.html, client/src/App.jsx, client/src/components/Footer/Footer.jsx, client/src/components/Loader/Loader.jsx, client/src/components/Paginator/Paginator.jsx, client/src/pages/ecommerce/Shop/Shop.jsx
fix de un ; por fuera del contenido
fix margin top footer eliminado
fix de !important en loader
fix altura del contenedor paginator
fix min-h-screen contenedor de filtros y paginator
=> fix App, Footer, Loader, Paginator, Filters and Paginator

client/src/App.jsx
=> fix lazy loading

client/src/components/Card/Card.jsx, client/src/components/ContainerRecomendados/ContainerRecomendados.jsx, client/src/pages/ecommerce/Forms/FormModifyStore/FormModifyStore.jsx
ESTO ESTA LISTO PARA MASTER, ES EL BANNER DE RECOMENDADOS QUE NO RENDERIZABA Y YA FUNCIONA
=> Pol ESTO ESTA LISTO PARA MASTER  "fix banner de recomendados en checkout, y otros detalles"

client/src/App.jsx, client/src/pages/ecommerce/StoreDetail/StoreDetail.jsx, client/src/pages/ecommerce/StoreDetail/adapters/qualificationAdapter.js, client/src/pages/ecommerce/StoreDetail/components/QualificationChart/QualificationChart.jsx
=> Stefano - StoreDetail con un componente y un adapter

client/src/pages/ecommerce/Success/Success.jsx
hay q modificar levemente el codigo antes de deployar
=> pagina sucess para deployar

api/src/controllers/invoicesController.js
para que traiga todos los datos de las compras
=> corregido el get a invoice 

api/src/handler/paymentHandler.js, client/src/pages/ecommerce/Profile/components/Purchase.jsx, client/src/pages/ecommerce/Success/Success.jsx, client/src/redux/features/users/usersActions.js, client/src/redux/features/users/usersSlice.js
ruta access para deploy  renderizado de nombre de producto, guardar factura en db,  redux para obtener las facturas
=> Imanol - ruta access para deploy  renderizado de nombre de producto, guardar factura en db,  redux para obtener las facturas

client/src/components/Card/Card.jsx, client/src/components/NavBar/components/DropdownShop.jsx
no renderiza el boton de delete y el confirmar compra, a menos que haya productos
=> Benja - Condicional en dropdown shop

client/src/pages/About/About.jsx, client/src/pages/ecommerce/LandingShop/LandingShop.jsx, client/src/pages/ecommerce/Profile/Profile.jsx, client/src/pages/ecommerce/Profile/components/Contacts.jsx, client/src/pages/ecommerce/Profile/components/PersonalInfo.jsx, client/src/pages/ecommerce/Profile/components/Ubication.jsx, client/src/pages/ecommerce/Shop/Shop.jsx, client/src/pages/ecommerce/Success/Success.jsx
fix scroll al renderizar window.scrollTo(0, 0) // fix descomentado de onclick de filtros
=> Imanol - fix scroll al renderizar window.scrollTo(0, 0) // fix descomentado de onclick de filtros

client/src/pages/ecommerce/Profile/components/Ubication.jsx
me olvide de borrar la direccion hardcodeada
=> fix direccion hardcodeada

client/src/main.jsx, client/src/pages/ecommerce/Shop/components/Filters/Filters.jsx, client/src/pages/ecommerce/Shop/components/Filters/components/List.jsx, client/src/pages/ecommerce/Shop/components/Filters/components/PriceRange.jsx, client/src/pages/ecommerce/Shop/components/Filters/components/rangeStyles.module.css, client/tailwind.config.cjs
=> Stefano - !! crear archivo .env en el front 

client/src/components/NavBar/components/DropdownShop.jsx, client/src/components/Paginator/Paginator.jsx, client/src/components/Paginator/components/Sort/Sort.jsx
el dropdown renderiza el mensaje cuando no hay productos
Estilos mejorados del sort y el paginador muestra el ultimo numero de pagina
=> Benja - Dropdown sin productos y estilos

client/src/App.css, client/src/components/Paginator/Paginator.jsx
cuando se cambia de pagina hace un scroll smooth hasta el principio y el paginador de abajo del shop muestra el ultimo numero de pagina que existe
=> Benja - Scroll smooth y paginations

client/src/pages/ecommerce/ProductDetail/ProductDetail.jsx, client/src/pages/ecommerce/Shop/components/Filters/Filters.jsx
no se puede seleccionar tamaño desde el detail entonces queda mal
=> Benja - Detail cambie "seleccione tamaño" por "tamaño"
